plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/git'
  - '@semantic-release/github'
  - '@semantic-release/npm'
branches:
  - 'master'
repositoryUrl: https://github.com/eduardoconti/api-pix.git