version: '3.7'
services:
  api-pix:
    container_name: api-pix
    restart: on-failure
    build: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: yarn start:dev
