version: '3.7'

services:
  api-pix:
    container_name: api-pix
    restart: on-failure
    build: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: yarn start:dev
    networks:
      - api-pix
    depends_on:
      - postgres
    dns:
      - 8.8.8.8

  postgres:
    image: postgres:alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: postgres
    volumes:
      - pg-apipix-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - api-pix
    restart: always
    dns:
      - 8.8.8.8
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - api-pix
    dns:
      - 8.8.8.8
networks:
  api-pix:

volumes:
  pg-apipix-data:
  redis:
